name: "hello"

on:
    push:
        paths:
            - ".github/workflows/**"
    workflow_dispatch:

jobs:
    sample:
        name: Hello
        runs-on: ubuntu-latest
        steps:
            - run: echo "Hello"