name: "workflow dispatch"

on:
    workflow_dispatch:

jobs:
    echo:
        name: "echo"
        runs-on: ubuntu-latest
        steps:
            - run: echo "${GITHUB_SERVER_URL}"
            - run: echo "${GITHUB_REPOSITORY}"
            - run: echo "${GITHUB_RUN_ID}"
            - run: echo "${GITHUB_WORKFLOW}"
            - run: echo "${GITHUB_EVENT_NAME}"
            - run: echo "${GITHUB_JOB}"
            - run: echo "${GITHUB_ACTION}"
            - run: echo "${GITHUB_ENV}"
            - run: echo "${GITHUB_STEP_SUMMARY}"
