name: "workflow dispatch"

on:
    workflow_dispatch:

jobs:
    echo:
        name: "echo"
        runs-on: ubuntu-latest
        steps:
            - run: |
              echo "${GITHUB_SERVER_URL}"
              echo "${GITHUB_REPOSITORY}"
              echo "${GITHUB_RUN_ID}"
              echo "${GITHUB_WORKFLOW}"
              echo "${GITHUB_EVENT_NAME}"
              echo "${GITHUB_JOB}"
              echo "${GITHUB_ACTION}"
              echo "${GITHUB_ENV}"
              echo "${GITHUB_STEP_SUMMARY}"