name: "workflow dispatch"

on:
    workflow_dispatch:

jobs:
    echo:
        name: "echo"
        runs-on: ubuntu-latest
        steps:
            - run: |
                echo "GITHUB_SERVER_URL: ${GITHUB_SERVER_URL}"
                echo "GITHUB_REPOSITORY: ${GITHUB_REPOSITORY}"
                echo "GITHUB_RUN_ID: ${GITHUB_RUN_ID}"
                echo "GITHUB_WORKFLOW: ${GITHUB_WORKFLOW}"
                echo "GITHUB_EVENT_NAME: ${GITHUB_EVENT_NAME}"
                echo "GITHUB_JOB: ${GITHUB_JOB}"
                echo "GITHUB_ACTION: ${GITHUB_ACTION}"
                echo "GITHUB_ENV: ${GITHUB_ENV}"
                echo "GITHUB_STEP_SUMMARY: ${GITHUB_STEP_SUMMARY}"
            - run: |
                echo "${{ secrets.SS_SEC_1 }}"

    job1:
        name: "job1"
        runs-on: ubuntu-latest
        steps:
            - run: echo "Job1"

    job2:
        name: "job2"
        runs-on: ubuntu-latest
        needs: job1
        steps:
            - run: echo "Job1 ${{ needs.job1.result }}"

    job3:
        name: "job3"
        runs-on: ubuntu-latest
        steps:
            - run: echo "Job3"
